//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlorOnlinePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPurchase
    {
        public int Cust_Purchase_ID { get; set; }
        public int Quantity_Order { get; set; }
        public int unit_price { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public byte[] Order_status { get; set; }
        public int Invoice_fk_Invoice_ID { get; set; }
    
        public virtual tbl_Invoice tbl_Invoice { get; set; }
    }
}
