//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlorOnlinePortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineIceCreamPortalEntities : DbContext
    {
        public OnlineIceCreamPortalEntities()
            : base("name=OnlineIceCreamPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Login> tbl_Login { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_IceCream_Category> tbl_IceCream_Category { get; set; }
        public virtual DbSet<CustomerPurchase> CustomerPurchases { get; set; }
        public virtual DbSet<tbl_IceCreamProduct_Vendor> tbl_IceCreamProduct_Vendor { get; set; }
        public virtual DbSet<tbl_Invoice> tbl_Invoice { get; set; }
        public virtual DbSet<tbl_IceCream_Product> tbl_IceCream_Product { get; set; }
    }
}
