//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlorOnlinePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Invoice()
        {
            this.CustomerPurchases = new HashSet<CustomerPurchase>();
        }
    
        public int Invoice_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Contact { get; set; }
        public System.DateTime Invoice_Add_On { get; set; }
        public string Invoice_Add_by { get; set; }
        public Nullable<System.DateTime> Invoice_Updated_On { get; set; }
        public string Invoice_Updated_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPurchase> CustomerPurchases { get; set; }
    }
}
