//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlorOnlinePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IceCream_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_IceCream_Category()
        {
            this.tbl_IceCream_Product = new HashSet<tbl_IceCream_Product>();
        }
    
        public int Cat_ID { get; set; }
        public string Cat_Name { get; set; }
        public System.DateTime Cat_Add_On { get; set; }
        public string Cat_Add_by { get; set; }
        public Nullable<System.DateTime> Cat_Updated_On { get; set; }
        public string Cat_Updated_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_IceCream_Product> tbl_IceCream_Product { get; set; }
    }
}
