//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlorOnlinePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        public int Login_ID { get; set; }
        public string UserName { get; set; }
        public string User_Password { get; set; }
        public int User_Type { get; set; }
        public int Emp_ID_fk_Emp_ID { get; set; }
    
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
