//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlorOnlinePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IceCream_Product
    {
        public int IceCream_ID { get; set; }
        public string IceCream_Name { get; set; }
        public string IceCream_Descrip { get; set; }
        public string IceCream_Image { get; set; }
        public int Stock { get; set; }
        public int unit_price { get; set; }
        public Nullable<int> Purchase_Price { get; set; }
        public Nullable<int> Sale_Price { get; set; }
        public System.DateTime IceCream_Add_On { get; set; }
        public string IceCream_Add_by { get; set; }
        public Nullable<System.DateTime> IceCream_Updated_On { get; set; }
        public string IceCream_Updated_By { get; set; }
        public int Cat_ID_fk_Cat_ID { get; set; }
        public int Vend_ID_fk_Vend_ID { get; set; }
    
        public virtual tbl_IceCream_Category tbl_IceCream_Category { get; set; }
        public virtual tbl_IceCreamProduct_Vendor tbl_IceCreamProduct_Vendor { get; set; }
    }
}
