//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlorOnlinePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Employee()
        {
            this.tbl_Login = new HashSet<tbl_Login>();
        }
    
        public int Emp_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Emp_Email { get; set; }
        public string Qualification { get; set; }
        public string Gender { get; set; }
        public string Emp_Contact { get; set; }
        public System.DateTime Emp_Add_On { get; set; }
        public string Emp_Add_by { get; set; }
        public Nullable<System.DateTime> Emp_Updated_On { get; set; }
        public string Emp_Updated_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Login> tbl_Login { get; set; }
    }
}
